# https://circleci.com/docs/2.0/config-intro/

version: 2.1

orbs:
  dt: cci-dep/dependency-tracking@0.0.1
  node: circleci/node@5.0

jobs:
  dependency-tracking:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: echo "your pipeline id is << pipeline.id  >>"
      - dt/track:
          pipeline_id: << pipeline.id >>
          path: "package-lock.json"
          revision: << pipeline.git.revision >>
          vcs_url: << pipeline.project.git_url >>
  js-build:
    docker:
      - image: cimg/node:14.18
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Running JS linting and unit test
          command: |
            npm run lint:js
            npm run test:js

  php-lint:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - run:
          name: Linting PHP
          command: |
            composer i
            composer lint

  php-test:
    parameters:
      php-version-number:
        type: string
    docker:
      - image: cimg/php:<< parameters.php-version-number >>
    steps:
      - checkout
      - run:
          name: Testing PHP
          command: |
            composer i
            composer test

  e2e-test:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Running e2e tests
          command: |
            npm run wp-env start
            npm run test:e2e
      - store_artifacts:
          path: artifacts

workflows:
  test-flow:
    jobs:
      - dependency-tracking
      - js-build
      - php-lint
      - php-test:
          requires:
            - php-lint
          matrix:
            parameters:
              php-version-number: [ '7.3', '7.4', '8.0', '8.1' ]
      - e2e-test
